# Generated by Django 6.0.4 on 2026-04-20 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Camisetas, Hoodies, Pantalones, Accesorios', max_length=50, unique=True, verbose_name='Categoría')),
                ('slug', models.SlugField(help_text='URL amigable (ej: camisetas, hoodies)', max_length=60, unique=True, verbose_name='Slug')),
                ('sort_order', models.IntegerField(default=0, help_text='Orden de aparición en filtros', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: XS, S, M, L, XL, XXL, 6M', max_length=10, unique=True, verbose_name='Talla')),
                ('code', models.CharField(help_text='Código corto para ordenamiento', max_length=5, unique=True, verbose_name='Código')),
                ('sort_order', models.IntegerField(default=0, help_text='Orden de aparición (0, 1, 2...)', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='URL amigable (se genera automáticamente)', max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos', max_digits=10, verbose_name='Precio (COP)')),
                ('product_type', models.CharField(choices=[('fabrica', 'Producto de fábrica'), ('coleccion_limitada', 'Colección limitada')], default='fabrica', help_text='"Producto de fábrica" o "Colección limitada"', max_length=20, verbose_name='Tipo de producto')),
                ('category', models.ForeignKey(help_text='Categoría a la que pertenece el producto', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(help_text='Nombre de la colección', max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='URL amigable (se genera automáticamente)', max_length=110, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descripción o inspiración de la colección', verbose_name='Descripción')),
                ('start_date', models.DateTimeField(blank=True, help_text='Fecha en que la colección comienza a ser visible (opcional)', null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, help_text='Fecha en que la colección deja de ser visible (opcional)', null=True, verbose_name='Fecha de fin')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', help_text='Borrador (no visible), Publicada (visible), Archivada (oculta)', max_length=20, verbose_name='Estado')),
                ('style_config', models.JSONField(blank=True, help_text='JSON con colores, fondos, tipografías para la colección', null=True, verbose_name='Configuración visual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('products', models.ManyToManyField(blank=True, help_text='Productos que pertenecen a esta colección', related_name='collections', to='products.product', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('sku', models.CharField(help_text='Código interno único (se genera automáticamente)', max_length=50, unique=True, verbose_name='SKU')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible (no puede ser negativo)', verbose_name='Stock')),
                ('image', models.ImageField(blank=True, help_text='Imagen de la variante', null=True, upload_to='products/variants/', verbose_name='Imagen')),
                ('is_portrait', models.BooleanField(default=False, help_text='Si es True, muestra esta imagen como destacada en el catálogo', verbose_name='Imagen destacada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.size', verbose_name='Talla')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de productos',
                'ordering': ['product', 'size__sort_order'],
                'unique_together': {('product', 'size')},
            },
        ),
    ]
