# Generated by Django 6.0.4 on 2026-04-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Camisetas, Hoodies, Pantalones, Accesorios', max_length=50, unique=True, verbose_name='Categoría')),
                ('slug', models.SlugField(help_text='URL amigable (ej: camisetas, hoodies)', max_length=60, unique=True, verbose_name='Slug')),
                ('sort_order', models.IntegerField(default=0, help_text='Orden de aparición en filtros', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(help_text='Nombre de la colección', max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='URL amigable (se genera automáticamente)', max_length=110, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descripción o inspiración de la colección', verbose_name='Descripción')),
                ('start_date', models.DateTimeField(blank=True, help_text='Fecha en que la colección comienza a ser visible (opcional)', null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, help_text='Fecha en que la colección deja de ser visible (opcional)', null=True, verbose_name='Fecha de fin')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', help_text='Borrador (no visible), Publicada (visible), Archivada (oculta)', max_length=20, verbose_name='Estado')),
                ('cover_image', models.ImageField(blank=True, help_text='Imagen que se mostrará en la tarjeta de la colección (recomendado: 800x600px)', null=True, upload_to='collections/covers/', verbose_name='Imagen de portada')),
                ('primary_color', models.CharField(blank=True, default='#c2a575', help_text='Color de botones, enlaces y acentos', max_length=20, verbose_name='Color principal')),
                ('secondary_color', models.CharField(blank=True, default='#8b5e3c', help_text='Color para hover y detalles', max_length=20, verbose_name='Color secundario')),
                ('background_color', models.CharField(blank=True, default='#ffffff', help_text='Color de fondo de la página de la colección', max_length=20, verbose_name='Color de fondo')),
                ('text_color', models.CharField(blank=True, default='#1a1a1a', help_text='Color principal del texto', max_length=20, verbose_name='Color de texto')),
                ('background_image', models.ImageField(blank=True, help_text='Imagen de fondo para la página de la colección', null=True, upload_to='collections/bg/', verbose_name='Imagen de fondo')),
                ('title_font', models.CharField(blank=True, default="'Inter', sans-serif", help_text='Ej: "Playfair Display", serif', max_length=100, verbose_name='Fuente de títulos')),
                ('effects_config', models.JSONField(blank=True, help_text='JSON para efectos avanzados (hover, animaciones)', null=True, verbose_name='Configuración de efectos')),
                ('custom_css', models.TextField(blank=True, help_text='CSS adicional para esta colección (solo si sabes lo que haces)', verbose_name='CSS personalizado')),
                ('style_config', models.JSONField(blank=True, help_text='JSON con configuración visual (se genera automáticamente desde los campos)', null=True, verbose_name='Configuración visual (legado)')),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Negro, Blanco, Rojo, Azul, Verde', max_length=30, unique=True, verbose_name='Color')),
                ('code', models.CharField(help_text='Ej: #000000, #FFFFFF, #FF0000', max_length=10, unique=True, verbose_name='Código hexadecimal')),
                ('sort_order', models.IntegerField(default=0, help_text='Orden de aparición en filtros (0, 1, 2...)', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='URL amigable (se genera automáticamente)', max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos', max_digits=10, verbose_name='Precio (COP)')),
                ('product_type', models.CharField(choices=[('fabrica', 'Producto de fábrica'), ('coleccion_limitada', 'Colección limitada')], default='fabrica', help_text='"Producto de fábrica" o "Colección limitada"', max_length=20, verbose_name='Tipo de producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Color del producto',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('sku', models.CharField(help_text='Código interno único (se genera automáticamente)', max_length=50, unique=True, verbose_name='SKU')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible (no puede ser negativo)', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de productos',
                'ordering': ['product', 'product_color__sort_order', 'size__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: XS, S, M, L, XL, XXL, 6M', max_length=10, unique=True, verbose_name='Talla')),
                ('sort_order', models.IntegerField(default=0, help_text='Orden de aparición (0, 1, 2...)', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'ordering': ['sort_order'],
            },
        ),
    ]
