# Generated by Django 6.0.4 on 2026-04-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Color de fondo de la página de la colección', max_length=20, verbose_name='Color de fondo'),
        ),
        migrations.AddField(
            model_name='collection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la página de la colección', null=True, upload_to='collections/bg/', verbose_name='Imagen de fondo'),
        ),
        migrations.AddField(
            model_name='collection',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen que se mostrará en la tarjeta de la colección (recomendado: 800x600px)', null=True, upload_to='collections/covers/', verbose_name='Imagen de portada'),
        ),
        migrations.AddField(
            model_name='collection',
            name='custom_css',
            field=models.TextField(blank=True, help_text='CSS adicional para esta colección (solo si sabes lo que haces)', verbose_name='CSS personalizado'),
        ),
        migrations.AddField(
            model_name='collection',
            name='effects_config',
            field=models.JSONField(blank=True, help_text='JSON para efectos avanzados (hover, animaciones)', null=True, verbose_name='Configuración de efectos'),
        ),
        migrations.AddField(
            model_name='collection',
            name='primary_color',
            field=models.CharField(blank=True, default='#c2a575', help_text='Color de botones, enlaces y acentos', max_length=20, verbose_name='Color principal'),
        ),
        migrations.AddField(
            model_name='collection',
            name='secondary_color',
            field=models.CharField(blank=True, default='#8b5e3c', help_text='Color para hover y detalles', max_length=20, verbose_name='Color secundario'),
        ),
        migrations.AddField(
            model_name='collection',
            name='text_color',
            field=models.CharField(blank=True, default='#1a1a1a', help_text='Color principal del texto', max_length=20, verbose_name='Color de texto'),
        ),
        migrations.AddField(
            model_name='collection',
            name='title_font',
            field=models.CharField(blank=True, default="'Inter', sans-serif", help_text='Ej: "Playfair Display", serif', max_length=100, verbose_name='Fuente de títulos'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='style_config',
            field=models.JSONField(blank=True, help_text='JSON con configuración visual (se genera automáticamente desde los campos)', null=True, verbose_name='Configuración visual (legado)'),
        ),
    ]
