# Generated by Django 6.0.4 on 2026-07-27 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['sort_order'], 'verbose_name': 'Color del producto', 'verbose_name_plural': 'Colores del producto'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], db_index=True, default='borrador', help_text='Borrador (no visible), Publicada (visible), Archivada (oculta)', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['start_date'], name='products_co_start_d_3342ae_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['end_date'], name='products_co_end_dat_05a9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='products_pr_product_a5a1ea_idx'),
        ),
    ]
