# Generated by Django 6.0.4 on 2026-08-03 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcolor_options_alter_collection_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='interactive_background',
            field=models.ImageField(blank=True, help_text='Imagen usada para delimitar las zonas clicleables que redirigen a productos', null=True, upload_to='collections/interactive/', verbose_name='Fondo interactivo'),
        ),
        migrations.CreateModel(
            name='InteractiveZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('x', models.DecimalField(decimal_places=2, help_text='Porcentaje horizontal desde el borde izquierdo (0-100)', max_digits=5, verbose_name='Posición X (%)')),
                ('y', models.DecimalField(decimal_places=2, help_text='Porcentaje vertical desde el borde superior (0-100)', max_digits=5, verbose_name='Posición Y (%)')),
                ('width', models.DecimalField(decimal_places=2, help_text='Ancho de la zona en porcentaje (0-100)', max_digits=5, verbose_name='Ancho (%)')),
                ('height', models.DecimalField(decimal_places=2, help_text='Alto de la zona en porcentaje (0-100)', max_digits=5, verbose_name='Alto (%)')),
                ('label', models.CharField(blank=True, help_text='Etiqueta opcional mostrada al hacer hover', max_length=100, verbose_name='Etiqueta')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_zones', to='products.collection', verbose_name='Colección')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('product_color', models.ForeignKey(help_text='Producto (y color) al que redirige esta zona', on_delete=django.db.models.deletion.CASCADE, related_name='interactive_zones', to='products.productcolor', verbose_name='Color del producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Zona interactiva',
                'verbose_name_plural': 'Zonas interactivas',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
