# Generated by Django 6.0.4 on 2026-08-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_collection_interactive_background_interactivezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='effects_config',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='style_config',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='title_font',
        ),
    ]
