# Generated by Django 6.0.4 on 2026-04-21 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Formato: ZCD-0001, ZCD-0002, ZCE-0001...', max_length=8, unique=True, verbose_name='Número de pedido')),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de seguimiento')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('customer_email', models.EmailField(blank=True, help_text='Para enviar confirmación y seguimiento', max_length=254, null=True, verbose_name='Correo electrónico')),
                ('shipping_address', models.TextField(verbose_name='Dirección de envío')),
                ('delivery_notes', models.TextField(blank=True, help_text='Ej: Dejar con el portero, llamar antes de llegar', verbose_name='Notas adicionales')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Suma de productos sin envío', max_digits=10, verbose_name='Subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='subtotal + shipping_cost', max_digits=10, verbose_name='Total')),
                ('is_paid', models.BooleanField(default=False, help_text='Indica si el cliente pagó contraentrega', verbose_name='Pagado')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('listo', 'Listo para envío'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('cancelled_reason', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('size_snapshot', models.CharField(max_length=10, verbose_name='Talla')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('stock_snapshot', models.PositiveIntegerField(help_text='Para auditoría', verbose_name='Stock en el momento')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='unit_price * quantity', max_digits=10, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Item del pedido',
                'verbose_name_plural': 'Items del pedido',
                'ordering': ['id'],
            },
        ),
    ]
