# Generated by Django 6.0.4 on 2026-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_session_id',
            field=models.CharField(blank=True, help_text='Identificador de la sesión/transacción en la pasarela de pagos', max_length=100, null=True, unique=True, verbose_name='ID de sesión de pago'),
        ),
    ]
