# Generated by Django 6.0.4 on 2026-06-17 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_session_id'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='stock_snapshot',
            field=models.PositiveIntegerField(blank=True, help_text='Para auditoría', null=True, verbose_name='Stock en el momento'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Producto + talla al momento de la compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant', verbose_name='Variante'),
        ),
    ]
