# Generated by Django 6.0.4 on 2026-07-27 18:34

from django.db import migrations, models


def set_empty_email_for_nulls(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(customer_email__isnull=True).update(customer_email='')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_stock_snapshot_and_more'),
    ]

    operations = [
        migrations.RunPython(set_empty_email_for_nulls, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Para enviar confirmación y seguimiento', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_session_id',
            field=models.CharField(blank=True, help_text='Identificador de la sesión/transacción en la pasarela de pagos', max_length=100, null=True, verbose_name='ID de sesión de pago'),
        ),
    ]
