# Generated by Django 6.0.4 on 2026-07-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_order_orders_ispaid_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_session_id',
            field=models.CharField(blank=True, help_text='Identificador de la sesión/transacción en la pasarela de pagos', max_length=100, null=True, unique=True, verbose_name='ID de sesión de pago'),
        ),
    ]
