# Generated by Django 6.0.4 on 2026-07-29 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_payment_session_id_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_session_id',
            field=models.CharField(blank=True, default='', help_text='Identificador de la sesión/transacción en la pasarela de pagos', max_length=100, verbose_name='ID de sesión de pago'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_session_id', ''), _negated=True), fields=('payment_session_id',), name='unique_payment_session_id'),
        ),
    ]
