# Generated by Django 6.0.4 on 2026-08-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('sin_registrar', 'Sin Registrar'), ('stripe', 'Stripe'), ('wompi', 'Wompi'), ('contraentrega', 'Contraentrega')], db_index=True, default='sin_registrar', help_text='Pasarela o medio de pago utilizado', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('wompi', 'Wompi')], max_length=20, verbose_name='Pasarela')),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='ID de transacción en pasarela')),
                ('gateway_session_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='ID de sesión/intención en pasarela')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_process', 'En proceso'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado del pago')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto cobrado')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('raw_request', models.JSONField(blank=True, default=dict, verbose_name='Payload recibido (webhook)')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta enviada a pasarela')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=20)),
                ('event_id', models.CharField(db_index=True, max_length=255, verbose_name='ID del evento en pasarela')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo de evento')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Evento de pago',
                'verbose_name_plural': 'Eventos de pago',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'gateway_transaction_id'], name='orders_paym_gateway_6e0e44_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'gateway_session_id'], name='orders_paym_gateway_1b879f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='orders_paym_status_83f434_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_transaction_id', ''), _negated=True), fields=('gateway', 'gateway_transaction_id'), name='unique_gateway_transaction_id'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentevent',
            unique_together={('gateway', 'event_id')},
        ),
    ]
