# Generated by Django 6.0.4 on 2026-08-15 17:27

from django.db import migrations


def backfill_payment_method(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')

    # Pedidos con intención de Stripe registrada
    Order.objects.filter(payment_session_id__gt='').update(payment_method='stripe')

    # Pedidos contraentrega (marcados como pagados sin sesión de pasarela)
    Order.objects.filter(payment_session_id='', is_paid=True).update(payment_method='contraentrega')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_method_payment_paymentevent_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_payment_method, migrations.RunPython.noop),
    ]
