sonar.projectKey=Jeremy-Duarte_Zicada
sonar.organization=jeremy-duarte
sonar.projectName=Zicada
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.python.version=3.14.3

sonar.exclusions=\
  **/migrations/**,\
  **/tests/**,\
  **/venv/**,\
  **/__pycache__/**,\
  **/*.pyc,\
  **/static/**,\
  **/media/**,\
  **/img/**,\
  **/images/**

sonar.coverage.exclusions=\
  **/settings.py,\
  **/wsgi.py,\
  **/asgi.py,\
  **/manage.py,\
  **/urls.py,\
  **/apps.py,\
  **/migrations/**,\
  **/tests.py,\
  **/tests/**,\
  **/__init__.py,\
  **/admin.py