# Generated by Django 6.0.4 on 2026-06-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Imagen de fondo para el hero (recomendado: 1920x1080px).', null=True, upload_to='landingpage/hero/', verbose_name='Imagen de fondo')),
                ('overlay_opacity', models.FloatField(default=0.5, help_text='Opacidad del overlay oscuro (0 = transparente, 1 = negro total).')),
                ('title_text', models.CharField(default='ZICADA', max_length=200, verbose_name='Texto del título')),
                ('title_font_family', models.CharField(default="'Inter', sans-serif", max_length=100, verbose_name='Fuente del título (CSS)')),
                ('title_font_size', models.CharField(default='4rem', max_length=20, verbose_name='Tamaño de fuente')),
                ('title_font_weight', models.CharField(default='800', max_length=20, verbose_name='Peso de la fuente')),
                ('title_line_height', models.CharField(default='1.2', max_length=20, verbose_name='Altura de línea')),
                ('title_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Color')),
                ('title_margin_bottom', models.CharField(default='1rem', max_length=20, verbose_name='Margen inferior')),
                ('subtitle_text', models.CharField(default='LA MODA SE VA, TU ESTILO PERMANECE', max_length=300, verbose_name='Texto del lema')),
                ('subtitle_font_family', models.CharField(default="'Inter', sans-serif", max_length=100, verbose_name='Fuente del lema')),
                ('subtitle_font_size', models.CharField(default='1.25rem', max_length=20)),
                ('subtitle_font_weight', models.CharField(default='400', max_length=20)),
                ('subtitle_line_height', models.CharField(default='1.5', max_length=20)),
                ('subtitle_color', models.CharField(default='#e5e5e5', max_length=20)),
                ('subtitle_margin_bottom', models.CharField(default='2rem', max_length=20)),
                ('button_text', models.CharField(default='Explorar Catálogo', max_length=50, verbose_name='Texto del botón')),
                ('button_url', models.CharField(default='/catalogo/', max_length=200, verbose_name='URL del botón')),
                ('button_style', models.CharField(default='bg-zicada-accent hover:bg-opacity-90', max_length=100, verbose_name='Clases CSS del botón')),
                ('content_alignment', models.CharField(choices=[('center', 'Centrado'), ('left', 'Izquierda'), ('right', 'Derecha')], default='center', max_length=20, verbose_name='Alineación del contenido')),
                ('section_height', models.CharField(default='100vh', max_length=20, verbose_name='Altura de la sección (ej: 100vh, 90vh, 700px)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Hero',
                'verbose_name_plural': 'Configuraciones del Hero',
                'ordering': ['order'],
            },
        ),
    ]
