# Generated by Django 6.0.4 on 2026-06-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroconfig_created_by_heroconfig_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroconfig',
            options={'ordering': ['sort_order'], 'verbose_name': 'Configuración del Hero', 'verbose_name_plural': 'Configuraciones del Hero'},
        ),
        migrations.RenameField(
            model_name='heroconfig',
            old_name='order',
            new_name='sort_order',
        ),
    ]
