# Generated by Django 6.0.4 on 2026-06-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_heroconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroconfig',
            name='button_style',
            field=models.CharField(default='bg-zicada-accent hover:bg-opacity-90', max_length=500, verbose_name='Clases CSS del botón'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='button_url',
            field=models.CharField(default='/catalogo/', max_length=500, verbose_name='URL del botón'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='subtitle_font_family',
            field=models.CharField(default="'Inter', sans-serif", max_length=255, verbose_name='Fuente del lema'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='subtitle_text',
            field=models.CharField(default='LA MODA SE VA, TU ESTILO PERMANECE', max_length=500, verbose_name='Texto del lema'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='title_font_family',
            field=models.CharField(default="'Inter', sans-serif", max_length=255, verbose_name='Fuente del título (CSS)'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='title_text',
            field=models.CharField(default='ZICADA', max_length=255, verbose_name='Texto del título'),
        ),
    ]
