# Generated by Django 6.0.4 on 2026-07-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_heroconfig_button_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroconfig',
            name='overlay_opacity',
            field=models.FloatField(default=0.5, help_text='Opacidad del overlay oscuro (0 = transparente, 1 = negro total).', verbose_name='Opacidad del overlay'),
        ),
    ]
