# Generated by Django 6.0.4 on 2026-07-30 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_heroconfig_overlay_opacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('description', models.CharField(help_text='Descripción corta de la fotografía.', max_length=255, verbose_name='Descripción')),
                ('image', models.ImageField(help_text='Imagen vertical recomendada (formato celular 9:16).', upload_to='landingpage/gallery/', verbose_name='Fotografía')),
                ('alt_text', models.CharField(help_text='Texto alternativo de la imagen para SEO y accesibilidad.', max_length=255, verbose_name='Texto alternativo (SEO)')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel de galería.', verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Fotos de Galería',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('title', models.CharField(blank=True, default='', help_text='Título opcional sobre la imagen.', max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, default='', help_text='Texto secundario opcional.', max_length=500, verbose_name='Subtítulo')),
                ('image', models.ImageField(help_text='Imagen del espacio publicitario (recomendado: 1920x800px).', upload_to='landingpage/promos/', verbose_name='Imagen publicitaria')),
                ('link_url', models.CharField(blank=True, default='', help_text='Destino al hacer clic (opcional).', max_length=500, verbose_name='URL del enlace')),
                ('link_text', models.CharField(blank=True, default='', help_text='Texto del CTA (opcional).', max_length=50, verbose_name='Texto del botón')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (se muestran máximo 3 activos).', verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Espacio Publicitario',
                'verbose_name_plural': 'Espacios Publicitarios',
                'ordering': ['sort_order'],
            },
        ),
    ]
