# Generated by Django 6.0.4 on 2026-08-10 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gallery_homepromo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(help_text='Ej: Grid 3x3, Mosaico 2x2.', max_length=100, verbose_name='Nombre del layout')),
                ('columns', models.PositiveSmallIntegerField(default=3, help_text='Número de columnas del grid (1-4).', verbose_name='Columnas')),
                ('rows', models.PositiveSmallIntegerField(default=3, help_text='Número de filas del grid (1-4).', verbose_name='Filas')),
                ('css_class', models.CharField(default='grid-cols-3', help_text='Clases Tailwind para el contenedor del grid.', max_length=100, verbose_name='Clase CSS')),
                ('max_photos', models.PositiveSmallIntegerField(default=9, help_text='Capacidad máxima del layout (columnas x filas).', verbose_name='Máximo de fotos')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la lista de layouts.', verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Layout de Galería',
                'verbose_name_plural': 'Layouts de Galería',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (no eliminado suavemente)', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('image', models.ImageField(help_text='Imagen de la galería (máximo 5MB).', upload_to='landingpage/gallery/photos/', verbose_name='Fotografía')),
                ('redirect_url', models.URLField(blank=True, default='', help_text='Destino al hacer clic (opcional).', verbose_name='URL de redirección')),
                ('title', models.CharField(blank=True, default='', help_text='Título o leyenda de la foto.', max_length=200, verbose_name='Título')),
                ('alt_text', models.CharField(help_text='Descripción para SEO y accesibilidad.', max_length=255, verbose_name='Texto alternativo (SEO)')),
                ('aspect_ratio', models.FloatField(blank=True, help_text='Ancho / alto detectado automáticamente.', null=True, verbose_name='Relación de aspecto')),
                ('aspect_category', models.CharField(blank=True, choices=[('square', 'Cuadrada'), ('portrait', 'Vertical'), ('landscape', 'Horizontal'), ('wide', 'Panorámica')], default='', help_text='Clasificación automática según la relación de aspecto.', max_length=20, verbose_name='Categoría de aspecto')),
                ('display_zone', models.CharField(blank=True, default='', help_text='Clases CSS de span de grid generadas automáticamente.', max_length=50, verbose_name='Zona visual')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la galería.', verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('layout', models.ForeignKey(blank=True, help_text='Layout explícito para esta foto (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='core.gallerylayout', verbose_name='Layout asignado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Fotos de Galería',
                'ordering': ['sort_order'],
            },
        ),
    ]
