# Generated by Django 6.0.4 on 2026-08-10 00:44

from django.db import migrations


def create_default_layouts(apps, schema_editor):
    """Crea los layouts de galería por defecto: 1x1, 2x2, 3x3 y 4x4."""
    GalleryLayout = apps.get_model('core', 'GalleryLayout')
    defaults = [
        {
            'name': 'Grid 1x1',
            'columns': 1,
            'rows': 1,
            'css_class': 'grid-cols-1 auto-rows-[300px]',
            'max_photos': 1,
            'sort_order': 1,
        },
        {
            'name': 'Grid 2x2',
            'columns': 2,
            'rows': 2,
            'css_class': 'grid-cols-2 auto-rows-[200px]',
            'max_photos': 4,
            'sort_order': 2,
        },
        {
            'name': 'Grid 3x3',
            'columns': 3,
            'rows': 3,
            'css_class': 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 auto-rows-[200px]',
            'max_photos': 9,
            'sort_order': 3,
        },
        {
            'name': 'Grid 4x4',
            'columns': 4,
            'rows': 4,
            'css_class': 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 auto-rows-[180px]',
            'max_photos': 16,
            'sort_order': 4,
        },
    ]
    for data in defaults:
        GalleryLayout.objects.get_or_create(
            name=data['name'],
            defaults={
                'columns': data['columns'],
                'rows': data['rows'],
                'css_class': data['css_class'],
                'max_photos': data['max_photos'],
                'sort_order': data['sort_order'],
                'is_active': True,
            },
        )


def remove_default_layouts(apps, schema_editor):
    """Elimina los layouts de galería por defecto."""
    GalleryLayout = apps.get_model('core', 'GalleryLayout')
    GalleryLayout.objects.filter(name__in=['Grid 1x1', 'Grid 2x2', 'Grid 3x3', 'Grid 4x4']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gallerylayout_galleryphoto'),
    ]

    operations = [
        migrations.RunPython(create_default_layouts, remove_default_layouts),
    ]
