# Generated by Django 6.0.4 on 2026-08-10 01:12

from django.db import migrations

ASPECT_PORTRAIT = 'portrait'
ASPECT_SQUARE = 'square'
ASPECT_LANDSCAPE = 'landscape'
ASPECT_WIDE = 'wide'

ZONES_BY_CATEGORY = {
    ASPECT_PORTRAIT: 'col-span-1',
    ASPECT_SQUARE: 'col-span-1',
    ASPECT_LANDSCAPE: 'col-span-2',
    ASPECT_WIDE: 'col-span-2',
}


def category_for_ratio(ratio):
    """Clasifica según la relación de aspecto (formatos de teléfono)."""
    if ratio is None:
        return ASPECT_SQUARE
    if ratio < 0.95:
        return ASPECT_PORTRAIT
    if ratio > 2.0:
        return ASPECT_WIDE
    if ratio > 1.15:
        return ASPECT_LANDSCAPE
    return ASPECT_SQUARE


def recalc_display_zones(apps, schema_editor):
    """Recalcula categoría y zona visual de fotos existentes desde su aspect_ratio."""
    GalleryPhoto = apps.get_model('core', 'GalleryPhoto')
    photos = GalleryPhoto.objects.exclude(aspect_ratio__isnull=True)
    for photo in photos:
        category = category_for_ratio(photo.aspect_ratio)
        photo.aspect_category = category
        photo.display_zone = ZONES_BY_CATEGORY[category]
        photo.save(update_fields=['aspect_category', 'display_zone', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gallery_default_layouts'),
    ]

    operations = [
        migrations.RunPython(recalc_display_zones, migrations.RunPython.noop),
    ]
