# Generated by Django 6.0.4 on 2026-08-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gallery_default_layouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryphoto',
            name='aspect_category',
        ),
        migrations.RemoveField(
            model_name='galleryphoto',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='galleryphoto',
            name='display_zone',
        ),
        migrations.RemoveField(
            model_name='galleryphoto',
            name='layout',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='display_size',
            field=models.CharField(choices=[('1x1', '1×1 — Rectangular / cuadrada'), ('2x2', '2×2 — Vertical (formato celular)')], default='1x1', help_text='1×1 para fotos rectangulares, 2×2 para verticales destacadas (formato celular).', max_length=3, verbose_name='Tamaño de celda'),
        ),
    ]
