from django.urls import path, include
from . import views

app_name = 'products'

admin_patterns = [
    path('tallas/', views.SizeListView.as_view(), name='size_list'),
    path('tallas/crear/', views.SizeCreateView.as_view(), name='size_create'),
    path('tallas/<int:pk>/editar/', views.SizeUpdateView.as_view(), name='size_edit'),
    path('tallas/<int:pk>/eliminar/', views.SizeDeleteView.as_view(), name='size_delete'),
    path('tallas/importar/', views.SizeImportView.as_view(), name='size_import'),
    path('tallas/plantilla/', views.size_template, name='size_template'),
    path('categorias/', views.CategoryListView.as_view(), name='category_list'),
    path('categorias/crear/', views.CategoryCreateView.as_view(), name='category_create'),
    path('categorias/<int:pk>/editar/', views.CategoryUpdateView.as_view(), name='category_edit'),
    path('categorias/<int:pk>/eliminar/', views.CategoryDeleteView.as_view(), name='category_delete'),
    path('categorias/importar/', views.CategoryImportView.as_view(), name='category_import'),
    path('categorias/plantilla/', views.category_template, name='category_template'),
    path('colores/', views.ColorListView.as_view(), name='color_list'),
    path('colores/crear/', views.ColorCreateView.as_view(), name='color_create'),
    path('colores/<int:pk>/editar/', views.ColorUpdateView.as_view(), name='color_edit'),
    path('colores/<int:pk>/eliminar/', views.ColorDeleteView.as_view(), name='color_delete'),
    path('colores/importar/', views.ColorImportView.as_view(), name='color_import'),
    path('colores/plantilla/', views.color_template, name='color_template'),
    path('imagenes/', views.ProductImageListView.as_view(), name='productimage_list'),
    path('imagenes/subir/', views.ProductImageCreateView.as_view(), name='productimage_create'),
    path('imagenes/<int:pk>/editar/', views.ProductImageUpdateView.as_view(), name='productimage_edit'),
    path('imagenes/<int:pk>/eliminar/', views.ProductImageDeleteView.as_view(), name='productimage_delete'),
    path('productos/', views.ProductListView.as_view(), name='product_list'),
    path('productos/crear/', views.ProductCreateView.as_view(), name='product_create'),
    path('productos/<int:pk>/editar/', views.ProductUpdateView.as_view(), name='product_edit'),
    path('productos/<int:pk>/eliminar/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('productos/<int:pk>/restaurar/', views.ProductRestoreView.as_view(), name='product_restore'),
    path('productos/papelera/', views.ProductTrashcanView.as_view(), name='product_trashcan'),
    path('productos/<int:product_pk>/colores/crear/', views.ProductColorCreateView.as_view(), name='productcolor_create'),
    path('productos/colores/<int:pk>/editar/', views.ProductColorUpdateView.as_view(), name='productcolor_edit'),
    path('productos/colores/<int:pk>/eliminar/', views.ProductColorDeleteView.as_view(), name='productcolor_delete'),
    path('productos/<int:product_pk>/variantes/crear/', views.ProductVariantCreateView.as_view(), name='productvariant_create'),
    path('productos/variantes/<int:pk>/editar/', views.ProductVariantUpdateView.as_view(), name='productvariant_edit'),
    path('productos/variantes/<int:pk>/eliminar/', views.ProductVariantDeleteView.as_view(), name='productvariant_delete'),
    path('productos/variantes/<int:pk>/restaurar/', views.ProductVariantRestoreView.as_view(), name='productvariant_restore'),
    path('productos/<int:product_pk>/variantes/papelera/', views.ProductVariantTrashcanView.as_view(), name='productvariant_trashcan'),
    path('colecciones/', views.CollectionListView.as_view(), name='collection_list'),
    path('colecciones/crear/', views.CollectionCreateView.as_view(), name='collection_create'),
    path('colecciones/<int:pk>/editar/', views.CollectionUpdateView.as_view(), name='collection_edit'),
    path('colecciones/<int:pk>/eliminar/', views.CollectionDeleteView.as_view(), name='collection_delete'),
    path('colecciones/<int:pk>/restaurar/', views.CollectionRestoreView.as_view(), name='collection_restore'),
    path('colecciones/papelera/', views.CollectionTrashcanView.as_view(), name='collection_trashcan'),
    path('colecciones/<int:pk>/zonas/', views.CollectionZoneEditorView.as_view(), name='collection_zones'),
    path('colecciones/<int:pk>/zonas/api/', views.CollectionZoneAPIView.as_view(), name='collection_zones_api'),
    path('colecciones/<int:pk>/zonas/api/<int:zone_pk>/', views.CollectionZoneDetailAPIView.as_view(), name='collection_zone_api_detail'),
]

urlpatterns = [
    path('stock-dashboard/', views.StockDashboardView.as_view(), name='stock_dashboard'),
    path('', views.ProductCatalogView.as_view(), name='catalog'),
    path('colecciones/', views.CollectionListViewPublic.as_view(), name='collections_list'),
    path('colecciones/<slug:slug>/', views.CollectionDetailView.as_view(), name='collection_detail'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    #Crud Paths
    path('admin/', include(admin_patterns)),
]