# Backoffice URLs
BACKOFFICE_DASHBOARD = 'backoffice:dashboard'
BACKOFFICE_ORDERS = 'backoffice:orders'
BACKOFFICE_PRODUCTS = 'backoffice:products'
BACKOFFICE_USERS = 'backoffice:users'
BACKOFFICE_CONFIG = 'backoffice:config'
BACKOFFICE_REPORT_GENERATOR = 'backoffice:report_generator'
BACKOFFICE_IMPORTERS_DASHBOARD = 'backoffice:importers_dashboard'

# Core URLs
CORE_HOME = 'home'
CORE_ABOUT = 'core:about'
CORE_CONTACT = 'core:contact'
CORE_CONTACT_SUCCESS = 'core:contact_success'
CORE_RETURNS_POLICY = 'core:returns_policy'
CORE_PRIVACY_POLICY = 'core:privacy_policy'
CORE_TERMS = 'core:terms'
CORE_STAFF_LOGIN = 'core:staff_login'
CORE_STAFF_LOGOUT = 'core:staff_logout'
CORE_HERO_LIST = 'core:hero_list'
CORE_HERO_CREATE = 'core:hero_create'
CORE_HERO_EDIT = 'core:hero_edit'
CORE_HERO_DELETE = 'core:hero_delete'
CORE_HERO_RESTORE = 'core:hero_restore'
CORE_HERO_TRASHCAN = 'core:hero_trashcan'

# Orders URLs
ORDERS_LIST = 'orders:order_list'
ORDERS_CREATE = 'orders:order_create'
ORDERS_DETAIL = 'orders:order_detail'
ORDERS_EDIT = 'orders:order_edit'
ORDERS_CONFIRM = 'orders:order_confirm'
ORDERS_CANCEL = 'orders:order_cancel'
ORDERS_ASSIGN_DELIVERY = 'orders:order_assign_delivery'
ORDERS_MARK_DELIVERED = 'orders:order_mark_delivered'
ORDERS_MARK_PREPARING = 'orders:order_mark_preparing'
ORDERS_MARK_READY = 'orders:order_mark_ready'
ORDERS_ITEM_CREATE = 'orders:orderitem_create'
ORDERS_ITEM_EDIT = 'orders:orderitem_edit'
ORDERS_ITEM_DELETE = 'orders:orderitem_delete'
ORDERS_DELIVERY_DASHBOARD = 'orders:delivery_dashboard'
ORDERS_TAKE_ORDER = 'orders:take_order'
ORDERS_DELIVER_ORDER = 'orders:deliver_order'
ORDERS_CART_ADD = 'orders:cart_add'
ORDERS_CART_REMOVE = 'orders:cart_remove'
ORDERS_CART_UPDATE = 'orders:cart_update'
ORDERS_CART_CLEAR = 'orders:cart_clear'
ORDERS_CART_DATA = 'orders:cart_data'
ORDERS_CART_DETAIL = 'orders:cart_detail'
ORDERS_CHECKOUT = 'orders:checkout'
ORDERS_CONFIRMATION = 'orders:order_confirmation'
ORDERS_TRACKING = 'orders:order_tracking'
ORDERS_CREATE_STRIPE_SESSION = 'orders:create_stripe_checkout_session'
ORDERS_STRIPE_WEBHOOK = 'orders:stripe_webhook'

# Products URLs (públicas)
PRODUCTS_STOCK_DASHBOARD = 'products:stock_dashboard'
PRODUCTS_CATALOG = 'products:catalog'
PRODUCTS_COLLECTIONS_LIST = 'products:collections_list'
PRODUCTS_COLLECTION_DETAIL = 'products:collection_detail'
PRODUCTS_DETAIL = 'products:product_detail'

# Products URLs (admin CRUD)
PRODUCTS_SIZE_LIST = 'products:size_list'
PRODUCTS_SIZE_CREATE = 'products:size_create'
PRODUCTS_SIZE_EDIT = 'products:size_edit'
PRODUCTS_SIZE_DELETE = 'products:size_delete'
PRODUCTS_SIZE_IMPORT = 'products:size_import'
PRODUCTS_SIZE_TEMPLATE = 'products:size_template'

PRODUCTS_CATEGORY_LIST = 'products:category_list'
PRODUCTS_CATEGORY_CREATE = 'products:category_create'
PRODUCTS_CATEGORY_EDIT = 'products:category_edit'
PRODUCTS_CATEGORY_DELETE = 'products:category_delete'
PRODUCTS_CATEGORY_IMPORT = 'products:category_import'
PRODUCTS_CATEGORY_TEMPLATE = 'products:category_template'

PRODUCTS_COLOR_LIST = 'products:color_list'
PRODUCTS_COLOR_CREATE = 'products:color_create'
PRODUCTS_COLOR_EDIT = 'products:color_edit'
PRODUCTS_COLOR_DELETE = 'products:color_delete'
PRODUCTS_COLOR_IMPORT = 'products:color_import'
PRODUCTS_COLOR_TEMPLATE = 'products:color_template'

PRODUCTS_IMAGE_LIST = 'products:productimage_list'
PRODUCTS_IMAGE_CREATE = 'products:productimage_create'
PRODUCTS_IMAGE_EDIT = 'products:productimage_edit'
PRODUCTS_IMAGE_DELETE = 'products:productimage_delete'

PRODUCTS_LIST = 'products:product_list'
PRODUCTS_CREATE = 'products:product_create'
PRODUCTS_EDIT = 'products:product_edit'
PRODUCTS_DELETE = 'products:product_delete'
PRODUCTS_RESTORE = 'products:product_restore'
PRODUCTS_TRASHCAN = 'products:product_trashcan'

PRODUCTS_COLOR_CREATE_FOR_PRODUCT = 'products:productcolor_create'
PRODUCTS_COLOR_EDIT_FOR_PRODUCT = 'products:productcolor_edit'
PRODUCTS_COLOR_DELETE_FOR_PRODUCT = 'products:productcolor_delete'

PRODUCTS_VARIANT_CREATE = 'products:productvariant_create'
PRODUCTS_VARIANT_EDIT = 'products:productvariant_edit'
PRODUCTS_VARIANT_DELETE = 'products:productvariant_delete'
PRODUCTS_VARIANT_RESTORE = 'products:productvariant_restore'
PRODUCTS_VARIANT_TRASHCAN = 'products:productvariant_trashcan'

PRODUCTS_COLLECTION_LIST = 'products:collection_list'
PRODUCTS_COLLECTION_CREATE = 'products:collection_create'
PRODUCTS_COLLECTION_EDIT = 'products:collection_edit'
PRODUCTS_COLLECTION_DELETE = 'products:collection_delete'
PRODUCTS_COLLECTION_RESTORE = 'products:collection_restore'
PRODUCTS_COLLECTION_TRASHCAN = 'products:collection_trashcan'
PRODUCTS_COLLECTION_STYLE = 'products:collection_style'

# Users URLs
USERS_LIST = 'users:user_list'
USERS_CREATE = 'users:user_create'
USERS_EDIT = 'users:user_edit'
USERS_CHANGE_PASSWORD = 'users:user_change_password'
USERS_DELETE = 'users:user_delete'
USERS_RESTORE = 'users:user_restore'
USERS_TRASHCAN = 'users:user_trashcan'
USERS_GROUP_LIST = 'users:group_list'
USERS_GROUP_CREATE = 'users:group_create'
USERS_GROUP_DETAIL = 'users:group_detail'
USERS_GROUP_EDIT = 'users:group_edit'
USERS_GROUP_DELETE = 'users:group_delete'
USERS_PROFILE = 'users:profile'
USERS_PROFILE_EDIT = 'users:profile_edit'
USERS_PROFILE_PASSWORD = 'users:profile_password'

# Delivery URLs (PWA para entregadores)
DELIVERY_MANIFEST = 'delivery:pwa_manifest'
DELIVERY_OFFLINE = 'delivery:offline'
DELIVERY_SERVICE_WORKER = 'delivery:service_worker'
DELIVERY_LOGIN = 'delivery:login'
DELIVERY_DASHBOARD = 'delivery:dashboard'
DELIVERY_ORDERS = 'delivery:orders'
DELIVERY_ORDER_DETAIL = 'delivery:order_detail'
DELIVERY_MARK_PAID = 'delivery:mark_paid'
DELIVERY_REGISTER_INCIDENCE = 'delivery:register_incidence'
DELIVERY_DAILY_SUMMARY = 'delivery:summary'
DELIVERY_CLOSE_JOURNEY = 'delivery:close_journey'
DELIVERY_API_ORDERS = 'delivery:api_orders'
DELIVERY_API_MARK_PAID = 'delivery:api_mark_paid'
DELIVERY_API_CREATE_INCIDENCE = 'delivery:api_create_incidence'